add support to Laravel 9
HCESrl/laravel-swagger-api pull request #14
Opened 2022-08-04 14:05 UTC by zabaala

2022-08-04 15:09 UTC, fsavina requested changes
@zabaala we cannot accept a PR with name and description modified

2022-08-04 16:01 UTC, zabaala commented
@fsavina changes were applied.
Sorry for that.

2022-08-05 06:31 UTC, fsavina approved these changes

2022-08-05 06:31 UTC, merged

2022-08-05 06:39 UTC, fsavina commented
Hi @zabaala, thanks for your contribution. You'll find it in the release v1.3.0